### ISSUE TITLE
Assistants developer documentation content plan ☂️

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/developer.sketch.com#9]
Take [existing content](https://www.notion.so/Create-custom-Assistant-Rules-f25686b938be45c595f1e29e95ad9cb6) from Notion and work into the following content plan, while making necessary (minor) tweaks for recent changes in the sketch-assistants `rc` branch.

:warning: For the duration of this umbrella, merge subtasks into [feature/9-assistant-docs-umbrella](https://github.com/sketch-hq/developer.sketch.com/pull/22) until we are ready to release.

#### Sidebar

- **Assistant Authoring Guides**
  - [x] Getting Started / Environment Setup #12 (@jedrichards)
  - [x] Writing a rule #13 (@jedrichards)
  - [x] Extending Existing Assistants #14 (@jedrichards)
  - [x] Running Assistants Locally (TDD and Local Assistants) #15 (@jedrichards)
  - [x] Publishing Assistants and Featuring on sketch.com #10 (@jedrichards)
  - [x] Handling Errors #16
- **Documentation**
  - [x] Core Concepts #17 (@christianklotz)
  - [x] Rule API #18 (@jedrichards)
  - [x] One click install links #19
  - [x] Assistants CLI #20
- [x] **Resources** #21
  - Link to sketch-assistants repo
  - Link to new assistant template repo
  - Link to file format TypeScript repo
  - Any more?

**Comment by christianklotz** [comment]
Looking good, do the best practices for ignoring, message writing and error handling all into Rule API or elsewhere?

**Comment by jedrichards** [comment]
@christianklotz Yes they could do, since those practices mainly revolve around specific methods in the Rule utils API, so could be discussed at that point. What did you have in mind for error handling? Not sure what specific pointers we can provide there ... generally any errors that happen in rules are caught, and then exposed in Sketch, so should be fairly self explanatory.

**Comment by christianklotz** [comment]
I suppose it's not just error handling but debugging an Assistant in general.

- Types of errors
- What happens if I throw an `Error` in my own implementation
- Get error details from within Sketch

**Comment by jedrichards** [comment]
Ah ok yeah, I've added a Handling Errors Guide, let's see how we go.
